server:
  port: 8081
  servlet:
    context-path:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hyunchoi@hist.co.kr
    password: sgglbprtchvgmuqm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
